### ISSUE TITLE
abswitch and onoffswitch have odd names/nesting

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#101]
From #96, @kathy-phet pointed out:

> we should work on a few name improvements. "abswitch" is not so friendly. It's also a bit odd that there is a double layer there - with abswitch and then onoffswitch both meaning the same thing. I realize one is the images and one is the toggle. Working on the names would help.

**Comment by samreid** [comment]
In discussion with @kathy-phet, we think it is best to provide the specific contextualized names for the columnSwitch (instead of abSwitch), but we will keep `aInputListener` as it is, because there is already sufficient context around the model Property change, and we don't want to provide too flexible a schema for sun components.

**Comment by samreid** [comment]
In the future, we may want to change the onOffSwitch to be better named. But that shouldn't be done before RC1.

**Comment by chrisklus** [comment]
For now, we renamed abSwitch to columnSwitch. Closing - remaining work related to this discussion over in https://github.com/phetsims/sun/issues/559.
