### ISSUE TITLE
First 2 screens break when setting SINGLE_COLUMN via studio

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#102]
From #96 @kathy-phet said:

> On the balancingAct.balanceLabScreen.model.columnStateProperty, should the model be limited on this screen to the 2 options of "DOUBLE COLUMN" and "NO COLUMNS" - it gets a bit funky if you select "SINGLE COLUMN".

**Comment by samreid** [comment]
Since this feature is powered by EnumerationIO and we have no support for taking a subset of enumeration valid values (and no plans to support that), maybe a reasonable alternative in this case would be to set this Property to be read only.  We have previously agreed that when there is an in-simulation control for a feature, it is not important/valuable to duplicate that control in studio.

**Comment by samreid** [comment]
I marked columnStateProperty as phetioReadOnly, and the user is no longer able to select a bad value from studio, while still being able to control the Property from the sim.  @kathy-phet is this a reasonable short-term and/or long-term solution?

**Comment by kathy-phet** [comment]
I think this is reasonable. But, if you want to toggle the state from the API - e.g. a smart computer program - does that mean it would not be possible to do so? (If that is the case, I think just leaving it as is would be better).

**Comment by samreid** [comment]
Thanks @kathy-phet, your comment reminded me we have another facility for this case called `phetioStudioControl` where we merely want to omit the studio control, but without marking a property entirely read-only.  We should try that next.
