### ISSUE TITLE
Improve copy pattern for masses

### ISSUE THREAD

**Issue by chrisklus** [phetsims/balancing-act#107]
@samreid and I found this line while working on https://github.com/phetsims/balancing-act/issues/96, and thought it was a little too clever and should be improved:

```js
createCopy: function() {
  // This clever invocation supports the creation of subclassed instances.
  return new this.constructor( this.positionProperty.get().copy(), this.isMystery );
}
```

We left a TODO that tags this issue.

**Comment by marlitas** [comment]
We can look at improving this code in the upcoming publication.

**Comment by jbphet** [comment]
@AgustinVallejo asked me about this, and I subsequently discussed it with @chrisklus.  @chrisklus and I asked ChatGPT how to create a method in a base class that could create copies of subclasses, and it suggested the same approach (i.e. the `this.constructor` thing).  Based on this, I don't think this is unreasonably "clever", so I'm going to update the docs, remove the TODO, and recommend closing this issue.

If I were starting over on this, or if I was tasked with rewriting it in a more current PhET style, I would get rid of the inheritance and just have a parameterized `ImageMass` class, and maybe a factory for creating the instances.  It just doesn't seem like we would gain enough by doing it now to make it worthwhile.

@AgustinVallejo - Back to you to for review.  If you're okay with it, please close.

**Comment by AgustinVallejo** [comment]
Thanks! It was a fun discussion. Closing.
