### ISSUE TITLE
Convert to the default layout bounds

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#109]
From https://github.com/phetsims/balancing-act/issues/73

@pixelzoom said:

> Does this sim have an issue to convert to DEFAULT_LAYOUT_BOUNDS? I recall that we decided to do that for all sims. @ariel-phet ?

@ariel-phet replied:

> It is certainly best to convert old sims to the new layout bounds when we revisit them. I don't think we necessarily decided to perform this work preemptively, but it would be appropriate for this simulation now that it is getting revisited.

**Comment by pixelzoom** [comment]
I stand corrected.  From https://github.com/phetsims/joist/issues/542#issuecomment-455300368:

> going forward we'll use default layoutBounds for everything, regardless of porting cost

And https://github.com/phetsims/joist/issues/542#issuecomment-456452635:

> As far I recall, we also decided not to go back through old sims and update their layout bounds.

**Comment by marlitas** [comment]
We can make this part of the work for the upcoming publication.

**Comment by AgustinVallejo** [comment]
Spoke with @jonathanolson and @zepumph, and we ended up changing providedOptions to optional in ScreenView.ts. So I'm undoing the last commit.

**Comment by marlitas** [comment]
I have similar concerns here to https://github.com/phetsims/arithmetic/issues/197

I'm starting to think this may be outside the scope of the region and culture work...

**Comment by marlitas** [comment]
I talked through Balancing Act with @jbphet and it seems like there's any easy entry point to just scale the MVT appropriately. I'm going to start there with Balancing Act to see if it's worth moving forward or any other scary things jump out.

**Comment by pixelzoom** [comment]
Per today's dev meeting and https://github.com/phetsims/arithmetic/issues/197#issuecomment-1846054254, should changes here be reverted?

**Comment by AgustinVallejo** [comment]
Changes reverted. Feel free to review and close @marlitas

**Comment by marlitas** [comment]
Yeah that looks great. Thanks @AgustinVallejo!
