### ISSUE TITLE
use default radius for ResetAllButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#110]
When #109 has been done (convert to DEFAULT_LAYOUT_BOUNDS), the ResetAllButton radius needs to be set to the default (which is supposed to be used across all sims).  That means deleting BASharedConstants. RESET_ALL_BUTTON_RADIUS.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/scenery-phet/issues/41 for ResetAllButton standardization history.

**Comment by samreid** [comment]
#109 is not in the purview of #96, unassigning for now.

**Comment by marlitas** [comment]
This can be looked into and potentially addressed as part of the work for #109

**Comment by AgustinVallejo** [comment]
Since #109 was essentially deferred, do we still want the default radius for ResetAllButton? Because it won't be consistent with the rest of the sim's scales. @pixelzoom @marlitas

**Comment by pixelzoom** [comment]
Also .. I don't recommend changing ResetAllButton radius. The button should be scaled.

**Comment by marlitas** [comment]
Looks good an straightforward. Thanks!
