### ISSUE TITLE
Mac Chrome metacog recording maybe? doesn't work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#114]
For https://github.com/phetsims/QA/issues/473.
While doing the recording nothing seemed to indicate a problem. However, the file that I got had a time stamp of about 2.5 minutes (it was probably closer to 40 sec. When trying to watch it, the video skipped to the end of the 40 seconds and then froze.
![chromeosproblem](https://user-images.githubusercontent.com/41024075/73797274-d2fc1f80-476c-11ea-8965-d7dfd70694d6.png)
The urls used are all the ones provided in https://github.com/phetsims/QA/issues/473.

**Comment by zepumph** [comment]
These feel like likely symptoms of some dropped events, but I see that playback wrapper didn't mark them as such. Can you record a few more sessions with ChromeOS to see if it was a fluke with the session, or something more systemic to worry about?

**Comment by KatieWoe** [comment]
Ok. I'm leaving a bit so I'll need to finish it up tomorrow. Sorry about that.

**Comment by KatieWoe** [comment]
Looking at this again, I don't think it was ChromeOS. It looks like a Mac test I don't recognize. I just thought it the ChromeOS test because that was the last one I did. Looking at the tests from @lmulhall-phet there is one at the end from a Mac that has problems. I don't think there is a problem with ChromeOS from this info.
![sameproblem](https://user-images.githubusercontent.com/41024075/73871167-9a128800-480a-11ea-95a5-97bdd79f0576.png)

**Comment by zepumph** [comment]
Good to know thanks!

**Comment by KatieWoe** [comment]
Not sure what is causing the problems we're seeing. Let me know if there is any testing you want done to narrow it down.

**Comment by KatieWoe** [comment]
I do notice that any recordings that odd recordings seem to Mac Chrome?

**Comment by kathy-phet** [comment]
@samreid - Can you update Karen on this - since Mac Chrome *is* the platform she is using?

**Comment by samreid** [comment]
@chrisklus and @zepumph and I reviewed the file that @KatieWoe emailed, and found that:

* For session 24, there is a `browserTabVisibleProperty: false` after 2 seconds which changes back to true after around 40 seconds.  The playback wrapper doesn't know how to depict this, so it shows the time jump and pause.  But after that the playback continues nicely.  We could improve showing `browserTabVisibleProperty: false` in the future.
* For session 33, it was recorded with `phetioEmitHighFrequencyEvents: false` so it can be used for data analysis but not for visual playback.

**Comment by samreid** [comment]
We opened a new issue for the playback wrapper depicting "tabbing away", and it seems everything else in this issue has been addressed.  Closing.
