### ISSUE TITLE
Troubles from 1.2 published for phet-io (but not phet brand)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/balancing-act#118]
IIRC, it was decided that we wouldn't be skipping deploying the phet brand on shared branches. The website is reporting 1.1 latest for phet brand, and 1.2 latest for phet-io brand, leading to complications in the maintenance process, where most notably the normal deployment procedures can't be used (since it would deploy 1.2 phet-brand).

Is this planning on being resolved (1.2 being published with the phet brand?)

**Comment by samreid** [comment]
My understanding from the conversation in https://github.com/phetsims/balancing-act/issues/105 was that we should publish 1.2 for phet-io brand only, and not phet brand.  @jonathanolson can you quantify this trouble this is causing?  Would you recommend the phet brand version be RC'd and published before the next maintenance release?  If we cannot afford to do that (say an imminent maintenance release must be done and we cannot get 1.2 phet brand published in that time frame), what would the workaround be, if any?

After responding, please assign to @ariel-phet to help prioritize and schedule.

**Comment by jonathanolson** [comment]
I've patched the maintenance process above to handle this. It was treated as an "unreleased" branch since it was a greater version than the production phet-brand release. Now it's treated as "released, use the phet-io data".

If this is something that we generally should support, it shouldn't be difficult but I'll need to know. @ariel-phet thoughts?

**Comment by ariel-phet** [comment]
@jonathanolson unfortunately, I think we will need to support this in general, as with all the client requests this will likely not be a unique case.

**Comment by zepumph** [comment]
I ran into this while working on https://github.com/phetsims/perennial/issues/318, it looks like I still have an unreleased branch for balancing-act 1.2:

```
    {
      "repo": "balancing-act",
      "branch": "1.2",
      "brands": [
        "phet",
        "phet-io"
      ],
      "isReleased": false
    },
```

**Comment by zepumph** [comment]
For this particular case, I believe we can mark the 1.2 as `ignoreForAutomatedMaintenanceReleases`, but we should investigate why the above commit isn't working.

**Comment by zepumph** [comment]
>@jonathanolson unfortunately, I think we will need to support this in general, as with all the client requests this will likely not be a unique case.

This is likely true, but for the most part we want to keep publications in sync. So likely we will be able to manually handle this case for research/etc using the `ignoreForAutomatedMaintenanceRleases` flag.

> but we should investigate why the above commit isn't working.

Ahh, It is because Balancing Act 1.2 is no longer in the active list in the PhET-iO metadata. I feel like that is correct, and we shouldn't care about inactive items in the metadata. So I added the flag. Then I reran `m.loadAllMaintenanceBranches(true)` which forces a cache break and recalculates unreleased branches, and balancing-act 1.2 was no longer in the list. I will go ahead and close
