### ISSUE TITLE
Document why removal must be guarded, or remove the guard

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#124]
In https://github.com/phetsims/axon/issues/332 we removed the guard from createObservableArray removal methods.  I added a sim-specific guard in the following commit, but I'm not sure if it should be documented or eliminated.  Assigning to responsible dev to take a look:

https://github.com/phetsims/balancing-act/commit/6d57445c54070f0e0550fb3423e7f39ab8fae5b6

**Comment by jbphet** [comment]
The guard was there because the code wasn't properly removing a listener when masses were removed from the plank.  I fixed that, and removed the guard.  Should be good to go, closing.
