### ISSUE TITLE
Redeploy from main branch

### ISSUE THREAD

**Issue by jbphet** [phetsims/balancing-act#127]
There are a number of issues related to multi-touch that have been fixed for this sim.  The changes were fairly extensive, and took advantage of some updates to common code, so I'd like to redeploy from master rather than trying to propagate the changes to the release branch.

@samreid and @zepumph - You've done some work in this repo recently to create special test versions for some work that was being done at Stanford.  I have two questions for you:
- Do you know of any reason *not* to deploy the PhET brand version from master?
- I'm assuming that when I redeploy, I should only do the PhET brand and not phet-io.  Is that correct?

Please assign back to me once these questions are answered.

**Comment by samreid** [comment]
Initial instrumentation for a client was done in https://github.com/phetsims/balancing-act/issues/96, and the custom version was delivered to a client in June 2020.  I don't believe the client will need any of the multi-touch fixes.  The changes should be safe for the PhET brand version.

In brief, I don't know any reason not to work on deploying PhET brand (but I don't remember how rigorous QA was after our changes in 2020, but hopefully nothing major was disturbed).  And I think we should only deploy the PhET brand version.  Balancing act is not listed in our published phet-io sim list, and is not listed in near-term quarterly goals.

**Comment by marlitas** [comment]
This is being handled with the upcoming region and culture publication. Yay!

**Comment by Luisav1** [comment]
Closing as the new RC branch has been created now.
