### ISSUE TITLE
Use scenery-phet.SkyNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#128]
From https://github.com/phetsims/scenery-phet/issues/79#issue-44468162:

> Currently, many sims with sky node exhibit the same bug as phetsims/fluid-pressure-and-flow#87 including BalancingAct.

While working on correcting this problem, I noticed that balancing-act is not using SkyNode.  Should it be?

It currently has its own implementation, OutsideBackgroundNode.

**Comment by jbphet** [comment]
@pixelzoom said:

> [balancing-act] currently has its own implementation, OutsideBackgroundNode.

`OutsideBackgroundNode` is, I believe, a common code node in scenery-phet that uses the aforementioned `scenery-phet.SkyNode` in conjunction with a `scenery-phet.GroundNode` to create a background with both ground and sky.  So, I'm thinking the implementation in balancing-act is fine as is.  My guess is that @pixelzoom didn't realize that `OutsideBackgroundNode` was a scenery-phet thing.

Right?

**Comment by pixelzoom** [comment]
Yeah, that must've been it.  Sorry for not digging deeper - for context, my quick review was for an ancient scenery-phet issue that I finally transferred to https://github.com/phetsims/fluid-pressure-and-flow/issues/335#issue-44468162.

Closing.
