### ISSUE TITLE
Entering page in studio focuses on seemingly random element

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#129]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/642. Found in https://phet-dev.colorado.edu/html/balancing-act/1.2.4-rc.1/phet-io/wrappers/studio.
When working in studio, when you enter a page in the sim, the tree focus should move to the top level of that page. However, here it seems to focus on some other element, such as the enabled property of the reset button or the enabled property of the next button in a tool box.

**Visuals**
![studioopenstorandomiterm](https://user-images.githubusercontent.com/41024075/117348814-eadabb80-ae67-11eb-84e0-5ce3c8210146.gif)

**Comment by jonathanolson** [comment]
I don't have any idea on this one, doesn't seem general. I'm going to unassign and not handle it during this maintenance process.

**Comment by jbphet** [comment]
@samreid and @zepumph - The balancing-act sim is a bit unique in that the phet-io instrumentation effort was done as a bit of a "rush job" to support a requested study, see #96 and #104.  I don't know at this point whether we are even providing Studio as part of this release, so I don't know how to evaluate the importance of fixing this GitHub issue.  I therefore need your input on it.  What would you recommend - does this issue need to be addressed or should it be deferred until a more complete phet-io instrumentation effort is done on this sim?

**Comment by samreid** [comment]
I'm not sure what explains this behavior, but it doesn't appear to be happening on master.  Perhaps it was a temporary bug that leaked into production.  In any case it doesn't seem severe or worth addressing in a maintenance release.  @jbphet thoughts?

**Comment by jbphet** [comment]
> @jbphet thoughts?

It's hard for me to contribute much at this point given my current knowledge of the situation, so let me ask some specific questions:

- Has this sim been released to the general phet-io-using public in phet-io form, or has it only been released to the specific individuals who requested it in support of their study?
- If it has not been generally released, do we know whether the people who are using it are using Studio?

If the answer to either one of these questions is yes, we should probably do a bit more investigation.  If both are a "no", then I think I would recommend closing without fixing.

**Comment by samreid** [comment]
Since balancing act is not mentioned in the PhET-iO links spreadsheet, I think that means it has not been shared to clients generally.

**Comment by KatieWoe** [comment]
Saw this a bit in https://github.com/phetsims/QA/issues/649 in the graphing quadratics sim

**Comment by samreid** [comment]
Closing based on the recommendations above.
