### ISSUE TITLE
Decide whether to turn off UI sounds on next publication

### ISSUE THREAD

**Issue by markgammon** [phetsims/balancing-act#133]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by marlitas** [comment]
This also came up in a couple of other sims in the region and culture work. We should have a conversation about sound for those sims in general.

**Comment by amanda-phet** [comment]
Discussed 12/7/23 and this sim should have sound design for the interaction of picking up and placing objects along the "number line" of the plank if we want to have UI sounds on. 

Just keep the game feedback sounds for now. 

As a side note, the "number line" sounds in Center and Variability could work well here!

**Comment by AgustinVallejo** [comment]
The above commit disables standard UI sounds, and keeps the game sounds in place. Please make sure this is what was sought after.

Assigning back to @amanda-phet and @marlitas. Whoever reviews first can close this issue, if ready.

**Comment by marlitas** [comment]
That sounds like what I would expect if we're only turning game sounds on so I think it's good to close.
