### ISSUE TITLE
Replace sim-specific code with LevelSelectionButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#135]
Related to https://github.com/phetsims/vegas/issues/108 ...

LevelSelectionButtonGroup is a new vegas UI component for creating the level-selection buttons for games.  It replaces boilerplate code in sims, and provides a consistent PhET-iO tandem structure.  Please convert this sim to use LevelSelectionButtonGroup.

**Comment by jbphet** [comment]
Deferring this until the next time this sim needs to be published from master.  At that point, this issue should be un-deferred and addressed.

**Comment by Luisav1** [comment]
This sim now uses the `LevelSelectionButtonGroup` to arrange the buttons but since that arranges the buttons placement itself, the layout did shift ever so slightly. For that reason I'd like @marlitas or @AgustinVallejo to review to ensure it's alright, thanks.

**Comment by AgustinVallejo** [comment]
Looking good! Closing
