### ISSUE TITLE
Address TODOs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#139]
There were some TODO that did not reference GitHub issues, so were failing the "todo-should-have-issue" lint rule. They are temporarily referencing this issue.

**Comment by AgustinVallejo** [comment]
All the TODOs that were addressing this issue have been either resolved or moved to a new issue. In a couple of cases (PositionIndicatorChoice.js and ColumnState.js) I just added the documentation that seemed reasonable for those files, perhaps if someone with more knowledge of the sim could review and maybe add a couple of lines on why those enumerations are important, that'd be great. @marlitas @Luisav1

**Comment by Luisav1** [comment]
@AgustinVallejo thanks, this looks great. Now that we're working on this sim, I've added info. on how these two states are kept track of on all screens of the sim, necessitating an enumeration. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by Luisav1** [comment]
Moved the remaining TODO references to the correct issue in area-model-common. Closing.
