### ISSUE TITLE
Add in Africa/ Modest, Asia, Oceania, and Latin America character sets

### ISSUE THREAD

**Issue by Luisav1** [phetsims/balancing-act#140]
This sim needs the structure for character sets and a preferences dialog.

**Comment by amanda-phet** [comment]
We'll be using SVGs for all of the characters for this sim. 

As part of this work, do we want to update all the the images here to be svg as well? And re-drawn by Mariah?

**Comment by amanda-phet** [comment]
I see that the mipmaps folder is reorganized to allow the new regions, but since these are svg I thought I'd see the folders in /images. 

I am thinking we should see /images/usa, etc. 

There are a LOT of "objects" in images, though. Should we make a folder for objects? Or should they still live in the root folder?

**Comment by Luisav1** [comment]
I think we could make a folder for objects, leave the screen icons in the root folder, and as well I'll make the regional folders in /images.

**Comment by Luisav1** [comment]
@amanda-phet Balancing Act is now ready for the artwork to be uploaded.

**Comment by amanda-phet** [comment]
Thanks for making those folders @Luisav1 ! 

All of the people are now uploaded. I still need to do the screen icons, but will need the updated objects before I can complete that. 

These changes will need to be made to the code: 
womanSitting is 5px wider on the left, so the offset will need to change by 5px
manSitting is 14.5px wider total, 5.5px wider on the left and 9px wider on the right, so the offset will need to change by 3.5px.

**Comment by amanda-phet** [comment]
As part of this work, should we have regional screen and game icons @kathy-phet ? There is one screen icon and two game icons that use characters.

**Comment by kathy-phet** [comment]
What do you think about simplifying the game icons to have no people in the icons - just adding more of the fun objects - and then internationalizing the screen icon with the person.

**Comment by amanda-phet** [comment]
I can just use objects on the game icons, sure, and will make screen icons reflective of the different regions. Thanks!

**Comment by amanda-phet** [comment]
@Luisav1 I have the screen and game icons ready. I'd like to try using the same icon for both the home screen and nav bar, so for example instead of gameIcon.png and gameIconSmall.png we should use gameIcon.svg for both. Let's try it out and see if it works!

**Comment by amanda-phet** [comment]
Screen icons are uploaded to the /images directory, with the Lab screen icons in regional folders. The game level icons are also in the /image directory, but the originals are in /mipmaps. Let me know if you have any questions about where any of the files live!

**Comment by Luisav1** [comment]
Closing since all the character sets are added in and integrated well.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by Luisav1** [comment]
Closing since it seems there are no TODOs pointing to this issue anymore.
