### ISSUE TITLE
reset all button is in a weird location

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/balancing-act#148]
![image](https://github.com/phetsims/balancing-act/assets/7852916/ed34e5ee-9847-4527-aa17-39895ab8d055)

**Comment by Luisav1** [comment]
The reset button is now in the right position in all screens.
![image](https://github.com/phetsims/balancing-act/assets/52978048/0f516767-24f1-4743-8fab-4f5b609622bb)
![image](https://github.com/phetsims/balancing-act/assets/52978048/5848b17d-5bfe-4ca6-80f9-70ba2fdbbe07)
Closing.
