### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by Luisav1** [phetsims/balancing-act#150]
While meeting, we realized AM sims don't have a `gameLevels` query parameter, similar to https://github.com/phetsims/graphing-lines/issues/144.

**Comment by pixelzoom** [comment]
Since I was on a roll and doing this for all of my sims, I went ahead and did this sim too.  Ready for review as part of the Region & Culture publication.

**Comment by amanda-phet** [comment]
Looks good!
