### ISSUE TITLE
"Select Level" string should be translatable

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#159]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1073, on the Game Screen the "Select Level" string isn't being translated when I change locale.

**Visuals**
<img width="948" alt="Screenshot 2024-04-23 at 8 45 01 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/41130ced-cce8-4220-bbf0-43e059343ed1">

**Comment by Luisav1** [comment]
This is now fixed in the commit above. Below is what it looks like:
![image](https://github.com/phetsims/balancing-act/assets/52978048/49526862-53d8-4dff-91b9-62734bebe218)
Closing.
