### ISSUE TITLE
Panel layout, alignment, and corner curvature needs consistency / changes from published version

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/balancing-act#160]
@Luisav1 - I noticed that in the dev version that just went through testing, the panels on the right have changed alignment. See images below: 
In dev version: 
- bottom panel is less wide than top panels 
- curvature of the corners is different from top panels
This needs a bit of pixel polishing to get things consistent  
![image](https://github.com/phetsims/balancing-act/assets/5096804/1108f94c-7aa5-4d8c-86e0-3072d7c7abb8)

Here is now the published version: 
![image](https://github.com/phetsims/balancing-act/assets/5096804/880a141f-d932-4a4c-8189-433a03010507)

**Comment by Luisav1** [comment]
Thanks for catching that @kathy-phet. I increased the mass carousel's width and corner radius to match the panels in the commit above. This is what it looks like now:
![image](https://github.com/phetsims/balancing-act/assets/52978048/f55fba70-03fd-498e-9a3a-53bd31a1334e)
Closing.
