### ISSUE TITLE
Text layout in game level banner is odd

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#162]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1084, should the text (Level, Challenge, Score) in the top banner on a game level start on the left side like in other sims we recently published? And should the Start Over button be more to the right?

**Visuals**
Balancing Act:
<img width="1405" alt="Screenshot 2024-05-13 at 7 52 03 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/beb4e7f7-68dd-4c54-beb9-24b1c7437a4c">

Area Model Algebra:
<img width="1405" alt="Screenshot 2024-05-13 at 7 48 02 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/96cc8bfb-2640-46c7-a692-75ea49145e1d">

Graphing Lines:
<img width="1405" alt="Screenshot 2024-05-13 at 7 53 56 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/e15bcb63-0366-44b5-8b3e-8049a53c8a4d">

**Comment by Luisav1** [comment]
Thanks for catching that @Nancy-Salpepi! A PhET-wide decision was made to use custom layout bounds, and not the default ScreenView layout bounds here for multiple sims: https://github.com/phetsims/phet-io/issues/1939. The reason being that it was difficult as changes could break or disturb any phet-io instrumention. The sim-specific issue is here: https://github.com/phetsims/balancing-act/issues/109.
