### ISSUE TITLE
Mystery Box labels aren't always centered

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#163]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1084, on the Balance Lab Screen with stringTest=dynamic and with some locales (ex. Tibetan, Arabic) the labels on the mystery boxes are off-center.
Also, with ?stringTest=double and in some locales (ex. Tibetan), the labels go all the way to the black border. 

**Visuals**
<img width="406" alt="Screenshot 2024-05-13 at 9 17 53 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/aaa154b6-3e36-41ef-90ab-ee4d17c3e5af">

<img width="251" alt="Screenshot 2024-05-13 at 9 15 12 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/933fd1ab-b221-4724-8d5f-96e2d664e659">

<img width="289" alt="Screenshot 2024-05-13 at 9 13 24 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/e2385498-7b40-4212-93ad-e59db5f7d798">

StringTest=double:
<img width="181" alt="Screenshot 2024-05-13 at 8 54 39 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/1da6efb5-a8da-4996-ba5b-4c8ee3d46e37">
<img width="295" alt="Screenshot 2024-05-13 at 8 54 27 AM" src="https://github.com/phetsims/balancing-act/assets/87318828/e48655e8-e6da-487d-9798-7e5d36d2611c">

**Comment by Luisav1** [comment]
To address the label text touching the black border I add padding around the label text.
As for the centering, I added a listener that re-centers the label text within the rectangle whenever the string property changes.
This seems fixed now:
![image](https://github.com/phetsims/balancing-act/assets/52978048/06d69403-3b9d-42e8-b89f-61b2bfb52886)
![image](https://github.com/phetsims/balancing-act/assets/52978048/fd484990-6b79-4351-afc7-4c79954f99a3)

Leaving open for review by QA.

**Comment by Luisav1** [comment]
This has been cherry-picked into the 1.3 RC branch and is now ready for review.

**Comment by Nancy-Salpepi** [comment]
Looks nice in rc.2. Closing.
