### ISSUE TITLE
QA credits are missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#165]
For https://github.com/phetsims/qa/issues/1087 there aren't any QA credits listed. I also don't see any in the published version.

For this round of testing the QA credits should include: Jaron Droder, Clifford Hardin, Nancy Salpepi and Kathryn Woessner

**Comment by Luisav1** [comment]
@Nancy-Salpepi I looked at the history of the credits section and it appears that QA credits were unfortunately never added. I looked through other QA testing rounds specific to Balancing Act and found that Liam Mulhall was also involved back in 2020. So I suggest we also add him. @Nancy-Salpepi what do you think?

**Comment by Nancy-Salpepi** [comment]
I would definitely add Liam. 
@KatieWoe any other thoughts on who we should add?

**Comment by KatieWoe** [comment]
I'd be a bit surprised if Steele Dalton was never involved, but I'm not sure beyond that. May have spelled his name wrong.

**Comment by Luisav1** [comment]
Thanks, I've updated the QA credits and they now include: Steele Dalton, Jaron Droder, Clifford Hardin, Liam Mulhall, Nancy Salpepi, Kathryn Woessner. Closing.
