### ISSUE TITLE
update screenshots for 1.3.0 release

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#166]
Screenshots need to be updated.

**Comment by Nancy-Salpepi** [comment]
Screenshots taken. @KatieWoe can you please upload for me? 

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/EmIYcFuEf4JOpsYNVdN-PLcBVFnIqtR1DQ5SU6E2KqHMig?email=Kathryn.Woessner%40Colorado.EDU&e=lLFZvL

**Comment by KatieWoe** [comment]
Screenshots uploaded

**Comment by Nancy-Salpepi** [comment]
@Luisav1 the screenshots have been updated!

**Comment by Luisav1** [comment]
Awesome, thanks! These look great to me, @amanda-phet did you want to take a look?

**Comment by amanda-phet** [comment]
These look great. 

The only one that I think we should re-do is balancing-act-screenshot-screen2.png. The beams should be off so we can see the slight tilt.

**Comment by Nancy-Salpepi** [comment]
whoops! Thanks for catching that @amanda-phet. Will do that now.

**Comment by Nancy-Salpepi** [comment]
@KatieWoe can you upload the updated balancing-act-screenshot-screen2.png for me?

**Comment by KatieWoe** [comment]
Done

**Comment by Luisav1** [comment]
The screenshots are updated in the 1.3 branch. Closing.
