### ISSUE TITLE
Remove workarounds for better handling of rotating text

### ISSUE THREAD

**Issue by jbphet** [phetsims/balancing-act#25]
Issue #16 reported that text appeared to "strobe" in Chrome and Firefox when rotating, which occurs quite a bit in this simulation.  Workaround have been implemented, and this ticket is to remind PhET to remove these workarounds if and when the browsers are improved such that rotating text is handled better.

**Comment by jbphet** [comment]
The main thing that needs to be done is to replace usages of RasterizedTextNode with regular Text, and to delete RasterizedTextNode.

**Comment by phet-steele** [comment]
@jbphet there are some noticeable issues in FF and Chrome. The text on Chrome "swims" around while FF text strobes. The catch is that this really only happens when the see saw is rotating slowly. Fast rotating text makes these issues less discernible.

**Comment by jbphet** [comment]
The fix looks good on some machines (my recent Dell, @jessegreenberg's recent Dell, @andrewadare's Mac) but looks bad on @phet-steele's somewhat older Lenovo Thinkpad.  In my opinion, the issues are still bad enough that I should revert to the rasterized text.

**Comment by jbphet** [comment]
Reminder: If and when the rotating text is changed back to being a regular Scenery text node, make the text on the masses pickable.  It was made unpickable due to issues with grabbing the rasterized text, see #60.

**Comment by marlitas** [comment]
This seems related to https://github.com/phetsims/balancing-act/issues/103. I'll keep open for QA to check in on this issue in the upcoming dev test.

**Comment by Nancy-Salpepi** [comment]
I don't see any issues with this in 1.3.0-dev.1 with mac + chromre/safari.

**Comment by KatieWoe** [comment]
Looks ok on Win 11 Chrome and Firefox to me. Closing
