### ISSUE TITLE
Sound is delayed in "Game" for Firefox

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balancing-act#26]
Test device: Mac Book13"
Operating System: osx 10.8
Browser: Firefox 29.0.1
Problem description:
When playing "Game" bell, spring, and trumpet sounds are delayed by a few seconds once question is answered or game is finished. 

Troubleshooting information (do not edit):

Name: Balancing Act

URL: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.0.0-rc.1/balancing-act_en.html

Version: 1.0.0-rc.1

Features missing: touch

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:29.0) Gecko/20100101 Firefox/29.0

Language: en-US

Window: 960x438

Pixel Ratio: 1/1

WebGL: WebGL 1.0

GLSL: WebGL GLSL ES 1.0

Vendor: Mozilla (Mozilla)

Vertex: attribs: 16 varying: 16 uniform: 1024

Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)

Max viewport: 8192x8192

OES_texture_float: true

**Comment by jbphet** [comment]
Just tested on Win 10 + Firefox 44.0.2, and there is no delay in the game sound.  Since no one has reported an issue on this for nearly two years, I'm closing the issue.
