### ISSUE TITLE
carousel buttons very light

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/balancing-act#37]
The carousel buttons seem too light and should probably be updated to have more contrast or a more 3-dimensional button feel.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to see if he has some suggestions on how to improve the color scheme, since I'm working on this sim at the moment but @amanda-phet is unavailable.

**Comment by jbphet** [comment]
Discussed with @ariel-phet, and we changed the button color and removed the stroke.  I'll assign to @amanda-phet to review in next release, but she is on leave, so if she doesn't respond I'll just close it.

**Comment by amanda-phet** [comment]
That button is certainly more obvious! :+1:
