### ISSUE TITLE
Some dependencies missing for version 1.0.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/balancing-act#42]
Version 1.0.1 is missing the dependencies for vegas and vibe.  This issue was revealed during investigation of issue #40.  This appears to have been corrected on the master branch, but apparently never propagated to the RC branch.  The sim should probably be redeployed as version 1.0.2 (a maintenance release) once this issue is corrected.

**Comment by jbphet** [comment]
Version 1.0.1 was release on May 16, 2014.  The SHAs from that date for the repos for which the dependencies were missing are:

vegas: be77758a944e62417ee6740c331252d207cac084
vibe: 6a72340d1944af36a3c782bc679e91e8bbc69617

I'll add these manually to the dependencies.json file on the 1.0 branch and regression test the sim.  In theory, these should be the same versions of these files that were deployed, so there should be no functional change.

**Comment by pixelzoom** [comment]
Sounds like we need something that checks package.json against config.js.  In code reviews, I frequently find that they do not match, due to a tendency to copy-paste, or to due to using simula-rasa without modifications.

**Comment by jbphet** [comment]
The SHA for the vegas repo listed above has lint errors, which were fixed in version 2f22bc042abed1a01101c1340c98ca0e743aad08, so I'll need to use this for v1.0.2.

**Comment by jbphet** [comment]
Regression testing complete, all looks good, going forward with maintenance release.  Closing this ticket.
