### ISSUE TITLE
branch: arch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#45]
I don't see any instances of 'together' or 'componentID' in balancing-act master.  So I'm guessing that perhaps the 'arch' branch is either something related to a specific study, or something vestigial that can be deleted.  @jbphet or @samreid can you please elaborate?

**Comment by samreid** [comment]
AFAIK it has outdated arch support (arch.start and arch.end) but hasn't got full-blown together support (addComponent, etc).  May be good to review and see if any of the arch work is worth updating.

**Comment by jbphet** [comment]
This branch was created in support of a study done with some of our collaborators at UBC.  It should be kept around for a while, at least until support for the newer version of interoperability is added to this sim.

**Comment by samreid** [comment]
@jbphet has described the branch above.  I'm not planning to work on the branch at the moment, so I'm unassigning the issue.

**Comment by samreid** [comment]
I skimmed through the branch, and it seems master is an improvement in terms of phet-io instrumentation, deleting branch and closing.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
