### ISSUE TITLE
Issue "?stringTest=double" covering objects

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balancing-act#47]
Testing for issue https://github.com/phetsims/tasks/issues/245
Mystery Object Container covers part of balance.
![screen shot 2015-05-26 at 11 25 18 am](https://cloud.githubusercontent.com/assets/5631059/7818692/6bc5b51c-039a-11e5-94d7-d5b37f30587f.png)
"What Will Happen?" in game mode covers Position options. 
![screen shot 2015-05-26 at 11 26 10 am](https://cloud.githubusercontent.com/assets/5631059/7818716/8e2c672c-039a-11e5-850d-7df6cf8b3261.png)

**Comment by jbphet** [comment]
Fixed most, if not all, of these issues in ce38902e3457728e4ae89ba7d467a06df29d87bf.

**Comment by elisemorgan** [comment]
Resolved in https://github.com/phetsims/tasks/issues/544

**Comment by elisemorgan** [comment]
@jbphet I can't close this issue, not sure what github changed

**Comment by phet-steele** [comment]
@elisemorgan try it now! I added QA to this repo and I want to check I did it right.

**Comment by elisemorgan** [comment]
Worked
