### ISSUE TITLE
Regression in layout

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/balancing-act#49]
Found this before making strut changes (in https://github.com/phetsims/scenery/issues/436), so I'm not sure what caused it.

![balancing-act-regression](https://cloud.githubusercontent.com/assets/480878/8136695/2fbad728-10fb-11e5-9c7f-1055e7334632.PNG)

**Comment by pixelzoom** [comment]
This is in balancing-act.

**Comment by pixelzoom** [comment]
Fixed this in https://github.com/phetsims/sun/commit/cec7fc906bdb209ba0938760f2e60eb25a59912d.

One (both?) of these panels are apparently also adding their own strut, which can be removed. Assigning to @jbphet to take care of that.

**Comment by jbphet** [comment]
This is fixed through common code changes (discussed with @pixelzoom) and changes to the sim code.  Closing.
