### ISSUE TITLE
Sky and ground are not infinitely long

### ISSUE THREAD

**Issue by arnabp** [phetsims/balancing-act#50]
When the window is shrunk horizontally (or extended vertically), the sky and ground end.

![screen shot 2015-06-16 at 3 35 05 pm 2](https://cloud.githubusercontent.com/assets/8583364/8195315/171c50ba-143f-11e5-96da-d462d6b9b3a4.png)

**Comment by jbphet** [comment]
This is true in other sims too, here's what it looks like in Forces and Motion Basics:

![famb-ground-and-sky](https://cloud.githubusercontent.com/assets/3082831/13793687/bb5b9c4e-eabd-11e5-928d-48b105b9d4d1.PNG)

**Comment by jbphet** [comment]
Discussed with @ariel-phet and decided not to address this one.  Closing.
