### ISSUE TITLE
invalid aspect ratio for screen icons in navbar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#51]
Screen icons for the navbar must have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE. See https://github.com/phetsims/joist/issues/263#issuecomment-121305888.  This sim does not, and fails when assertions are enabled.

**Comment by jbphet** [comment]
Fixed, closing.
