### ISSUE TITLE
Consider updating PhET girl and other people

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balancing-act#52]
@jbphet - when we go to redeploy this sim, we could have our graphic artist redo some of the people to be more consistent with our modern PhET girl. Really a question for you, if you have an attachment to the artwork, I am fine to leave as is.

**Comment by jbphet** [comment]
I'd love to see the artwork upgraded, please feel free to initiate that process.

**Comment by ariel-phet** [comment]
@jbphet it seems there are some important specs for the art work for instance, pixel size (so that it can be nicely mipmapped), as well as things like when seated, the tic mark tends to align well with the posterior of each character. Can you list out any important specs in this issue so the artwork will be a pretty seamless replacement for you?

**Comment by jbphet** [comment]
The artwork has been upgraded, and in order to make it work I took the initial versions of the new cartoon people and modified them to set well on the balance.  See #56 for details.  Closing.
