### ISSUE TITLE
Licensing for old-television?

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#53]
In the license.txt it said: old-television.png source=Open Clip Art notes=Modified by jblanco but in the commit message for the AI file it says "generated by PhET".  Which is true?  I couldn't find a close enough match when scanning through Open Clip Art.

**Comment by jbphet** [comment]
It was from Open Clip Art, I just modified it a lot, apparently enough that @samreid didn't recognize it.  The original can be found here: https://openclipart.org/detail/19995/antique-television.

I'm more than happy to create one from scratch if it helps with the licensing effort.  It would probably take me about 1/2 hr.

**Comment by samreid** [comment]
We are under minimal encumbrances from using public domain images, so there is no requirement to redraw this artwork.  I verified this appears in license.json properly now, thanks!  Closing.
