### ISSUE TITLE
can't enter new value on mass deduction challenges if wrong the first time

### ISSUE THREAD

**Issue by jbphet** [phetsims/balancing-act#55]
A bug seems to have crept into the master version of this sim where the mass entry dialog used in the mass deduction challenges becomes unpickable after an incorrect answer, and the originally entered value can't be updated.  This issue doesn't exist on the current live version (v1.0.2), so it must be due to some relatively recent change.

**Comment by rafaelrib** [comment]
The entry values works with google chrome and IE, but don't works in Maxthon browser.
To quick solve: It works when I use the paramenter: &rootRender:canvas.
But the canvas mode is so defocused when the embed size is small.

Summary: The entry value box depends of browser render engine type. It is working with Trident render. It isn't working with Webkit render.

I think that it could be solve using a render engine detection and if the browse is using webkit then force canvas mode render.

Something like:

if('WebkitAppearance' in document.documentElement.style){
    // detect WebKit
}
then  --force canvas mode render

I hope a solve for this box dialog bug that allows svg at Webkit browser, like occurs with the latest sim published at phet site.

**Comment by jbphet** [comment]
In order to fix this, I changed a line of code that used to set a layer's value to ```null``` to instead set it to ```true```.  The value of ```null``` was previously recommended by @jonathanolson as an optimization.  It must have worked at the time, because the currently published version of the sim doesn't exhibit the problem even though it contains this line of code.  My guess is that something changed in Scenery that caused the behavior to change.  Assigning to @jonathanolson to review and make sure that the solution is reasonable.

**Comment by jbphet** [comment]
I talked with @jonathanolson over Skype, and he said that what I did here was a reasonable solution for now but it seems to indicate that there is an issue in Scenery.  He intends to investigate, and will change the code in this sim back to setting pickability to null if and when he fixes it.  From this sim's point of view, there's nothing left to be done for this issue.  Closing.
