### ISSUE TITLE
use ScoreboardBar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#58]
See https://github.com/phetsims/build-an-atom/issues/110

**Comment by pixelzoom** [comment]
This came up in https://github.com/phetsims/chipper/issues/515#issuecomment-261584244:
>  ScoreboardPanel is deprecated, clients should use ScoreboardBar. There is 1 usage of ScoreboardPanel, in balancing-act (@jbphet).

**Comment by pixelzoom** [comment]
This looks pretty easy to do, probably just requires an OK from the design team, since it will change the look slightly.

**Comment by pixelzoom** [comment]
Here's the change... BalanceView line 182, replace `ScoreboardPanel instantiation` with:

```js
this.scoreboard = new ScoreboardBar(
      this.layoutBounds.width,
      gameModel.challengeIndexProperty,
      new Property( BalanceGameModel.PROBLEMS_PER_LEVEL ),
      gameModel.levelProperty,
      gameModel.scoreProperty,
      gameModel.elapsedTimeProperty,
      gameModel.timerEnabledProperty,
      function() { gameModel.newGame(); },
      {
        levelVisible: true,
        startOverButtonText: startOverString,
        font: new PhetFont( 14 ),
        centerX: this.layoutBounds.centerX,
        bottom: this.layoutBounds.maxY,
        leftMargin: 40,
        rightMargin: 40
      }
    );
```

Looks like this (with `?dev` to show the screen bounds)

![screenshot_74](https://cloud.githubusercontent.com/assets/3046552/20439401/8a3f645a-ad78-11e6-99de-2d21a4043c9d.png)
: 

Compared to `ScoreboardPanel` in published version (1.1.5):

![screenshot_75](https://cloud.githubusercontent.com/assets/3046552/20439422/ab57edce-ad78-11e6-83eb-aae39859098d.png)

**Comment by pixelzoom** [comment]
Credits in About dialog indicate that lead designers were "Kathy Perkins, John Blanco, Ariel Paul".  @kathy-phet @jbphet @ariel-phet May I make this change?  I moves the sim to PhET's modern scoreboard, and allows us to delete the deprecated (old) scoreboard.

**Comment by jbphet** [comment]
It looks okay to me, though I might try to make it a little less tall (i.e. reduce the yMargin value).  If I don't hear any objections from @ariel-phet or @kathy-phet by Monday 11/21/2016, I'll test it out, possibly tweak it a bit, and close this issue.

**Comment by pixelzoom** [comment]
@jbphet Since this is the last usage of ScoreboardPanel, can you also please remove ScoreboardPanel from vegas?

**Comment by jbphet** [comment]
Yes, will do.

**Comment by ariel-phet** [comment]
@pixelzoom @jbphet in most of the usages that I am aware of for ScoreboardPanel, we have been putting it at the top of the sim. and seeing it in context, I think that might also look/work better in this case. 

If that is an easy change, can we try that and I can look at it on master?

**Comment by pixelzoom** [comment]
@jbphet Since this doesn't seem to be high on your priority list, do you mind if I do it? So that we can continue to chip away at deleting deprecated code...

**Comment by ariel-phet** [comment]
@pixelzoom you have my permission to go ahead

**Comment by jbphet** [comment]
I'm fine with it.

**Comment by pixelzoom** [comment]
@jbphet @ariel-phet for your review:
http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.2.0-dev.1/balancing-act_en.html

I replaced ScoreboardPanel with ScoreboardBar, and located it at the top of the screen. See screenshot below.

@jbphet: The model-view transform was modified so that the origin moved down 42 pixels, the height of the ScoreboardBar.  Right aligning the scoreboard's "Start Over" button with `positionIndicatorControlPanel` (the "Positon" panel) seemed the most visually pleasing, and most adaptable to i18n.  So I nudged `positionIndicatorControlPanel` a few pixels to the right, and reduced `maxWidth` of the `challengeTitleNode` so that it looks reasonable with `?stringTest=long`.

![screenshot_234](https://cloud.githubusercontent.com/assets/3046552/20947075/bbac435e-bbca-11e6-9432-4a076e6647dc.png)

**Comment by ariel-phet** [comment]
@pixelzoom I think just two tweaks (which I believer are simple

Overall, I think the ScoreboardBar works well here, and definitely give some consistency with our other games.

Tweaks:
1. I feel like the blue of the ScoreboardBar should be a little darker jsut to add some more contrast with the sky (it is probably fine as is, so perhaps try darkening a bit, a shade or two), I will probably trust your judgement

2. To my eye, there needs to be a bit more negative space between the top of the play area and the ScoreboardBar (too many competing words). In this mockup I just move everything in the play area down a bit.

![ba](https://cloud.githubusercontent.com/assets/4051174/20948878/96813d4c-bbd3-11e6-949b-3c4df626eac5.PNG)

**Comment by ariel-phet** [comment]
@pixelzoom  Oh...and something happened to the word "position" in both the game screen and other screens in this version, the published version has a larger font.

**Comment by pixelzoom** [comment]
I didn't touch the font for 'Position', but it did seem odd to me.

**Comment by pixelzoom** [comment]
Note that the 'Position" font is unchanged from the screenshots in https://github.com/phetsims/balancing-act/issues/58#issuecomment-261588735, taken before I worked on this.

**Comment by ariel-phet** [comment]
@pixelzoom not pointing fingers, but if implementing this change lets also fix the font.

**Comment by pixelzoom** [comment]
Tracking 'Position' font in its own issue, https://github.com/phetsims/balancing-act/issues/78.

**Comment by ariel-phet** [comment]
Pulled master, changes to positioning and color look good

**Comment by pixelzoom** [comment]
Dev version is http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.2.0-dev.2/balancing-act_en.html

**Comment by pixelzoom** [comment]
Screenshot:

![screenshot_237](https://cloud.githubusercontent.com/assets/3046552/20949825/df1b5088-bbd8-11e6-884c-b80f5421705a.png)

**Comment by pixelzoom** [comment]
@ariel-phet Feel free to close this unless there's more to do.

**Comment by ariel-phet** [comment]
Looks good, closing
