### ISSUE TITLE
?stringTest=double issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-act#60]
Alright @jbphet, here's some things happening with ?stringTest=Double:

Game screen instructions cover the right panel (right panel still usable):
![ba dubs3](https://cloud.githubusercontent.com/assets/5863899/12460267/2d01a902-bf70-11e5-93d5-b3c276e9685e.PNG)

The carousel covers the seesaw on the 2nd screen:
![ba dubs2](https://cloud.githubusercontent.com/assets/5863899/12460279/4602396c-bf70-11e5-9474-76285d6f9446.PNG)

And last but not least, the mass labels are not handled well on the first screen. This is true throughout, but the first screen is good at demonstrating that the grab-able area increases with string size. This makes it hard to grab a desired object:

![balaac2](https://cloud.githubusercontent.com/assets/5863899/12460520/54e62fd2-bf71-11e5-84f7-86900af6f4ae.gif)

Tested on phettest, with Win 8.1 FF. For phetsims/tasks/issues/479
Not assigning to @jbphet  for the moment.

Troubleshooting information:
Name: ‪Balancing Act‬:‪Balancing Act‬
URL: http://phettest.colorado.edu/balancing-act/balancing-act_en.html?ea&brand=phet&stringTest=double
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
I fixed most, if not all, of the overlap issues in ce38902e3457728e4ae89ba7d467a06df29d87bf (but forgot to reference this issue in the commit).

**Comment by brroberts1231** [comment]
Text and carousel overlaps are fixed, but the problem with grabbing the desired object is still there, just to a lesser extent. Only happens when the objects are 2 marks apart rather than 6 as shown above, but it's still there. Tested on Win 7 chrome. 
for phetsims/tasks#544

**Comment by jbphet** [comment]
Oh, right.  The grabbing issue is due to the text rasterization, and was fixed when I de-rasterized the text, but then we decided to revert that change (see https://github.com/phetsims/balancing-act/issues/25) so this grab problem came back.  I'm not sure whether anything can be done about this, but I'll investigate.

**Comment by jbphet** [comment]
After discussing with @ariel-phet I went ahead and made the text unpickable for the masses, which fixes the issue with grabbing the objects in odd places.

**Comment by phet-steele** [comment]
@jbphet it's good!
