### ISSUE TITLE
Text overlaps on Safari with ?stringTest=double

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balancing-act#61]
Test device: Personal mac
Operating System: OSX 10.11
Browser: Safari 9.0
Problem description: "Position" and its options text overlap and text in the PhET menu as well as about "about" information
Screenshots:
<img width="455" alt="screen shot 2016-01-21 at 10 19 27 am" src="https://cloud.githubusercontent.com/assets/5631059/12488558/63a9f3e2-c029-11e5-9796-26bc44a1fc84.png">
<img width="545" alt="screen shot 2016-01-21 at 10 20 01 am" src="https://cloud.githubusercontent.com/assets/5631059/12488561/68f1aab6-c029-11e5-8924-bac830a03493.png">
<img width="922" alt="screen shot 2016-01-21 at 10 26 28 am" src="https://cloud.githubusercontent.com/assets/5631059/12488577/7b2f5e80-c029-11e5-8057-163d1508fb9c.png">

Troubleshooting information (do not edit):
Name: ‪Balancing Act‬:‪Balancing Act‬
URL: http://phettest.colorado.edu/balancing-act/balancing-act_en.html?ea&brand=phet&stringTest=double
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by phet-steele** [comment]
This issue is this:https://github.com/phetsims/scenery/issues/469
It was decided not to spend time on that issue.
