### ISSUE TITLE
stringTest=long

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/balancing-act#69]
Test device: Personal Mac 

Operating System: OS X 10.10.5

Browser: Safari 9.0.3 (10601.4.4)

Problem description: Long strings are funky on the ruler

Steps to reproduce: Perform long string test 

Severity: Minor

Screenshots:
![screen shot 2016-03-21 at 9 28 58 am](https://cloud.githubusercontent.com/assets/12610678/13923859/cdcc6096-ef47-11e5-9e9f-bad42d3dc496.jpg)

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.0-rc.1/balancing-act_en.html?stringTest=long
Version: 1.1.0-rc.1 2016-03-17 00:02:21 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
Language: en-us
Window: 1238x660
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"be39f3b6","branch":"master"},"balancing-act":{"sha":"85ea8af9","branch":"HEAD"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"3ffbd3a4","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"c84b3c41","branch":"HEAD"}}

**Comment by jbphet** [comment]
Unfortunately, adding scaling to this text messes up its positioning on this node due to the workarounds added for rotating text.  Since the sim doesn't break down in this case, and since very long strings actually work well until they get *extremely* long (as in this test case), I've decided not to fix this one.  Closing.
