### ISSUE TITLE
Check answer button with string "Next:Next"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-act#70]
@jbphet, the particular button on the game screen that says "Check", "Next", etc... does this when the string "Next:Next" is used:
![20160406_162848](https://cloud.githubusercontent.com/assets/5863899/14334922/d3decc9c-fc14-11e5-9ab4-37d9de8192ad.jpg)

This is happening on Tycho and Witten (iPad 2 iOS 9.3), and only when the string is explicitly this length. I don't mean "character length" where this string has 9 characters, I mean the literal length you'd measure with a ruler. It also only happens with NO other tabs open; so apparently screen size matters, too. Did not see this on Leibniz (iPad Air 2 iOS 9.3).

**Comment by phet-steele** [comment]
Troubleshooting information (do not edit):
Name: Next:Next
URL: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.0-rc.2/balancing-act_en.html?stringTest=Next:Next
Version: 1.1.0-rc.2 2016-04-05 21:07:08 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E233 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"d0dcba98","branch":"master"},"balancing-act":{"sha":"175d26be","branch":"HEAD"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"3ffbd3a4","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"c84b3c41","branch":"HEAD"}}

**Comment by jbphet** [comment]
This seems like a Scenery issue.  We've already decided that it shouldn't block publication since it only happens on one platform and not all the time there.  I'd like @jonathanolson to have a quick look to see if he has any immediate ideas about it.  @jonathanolson - the transparent part it where the highlight gradient normally shows up.

**Comment by jonathanolson** [comment]
No immediate thoughts. Does it happen with ?rootRenderer=canvas, or just with the default SVG?

**Comment by phet-steele** [comment]
no issue with ?rootRenderer=canvas

**Comment by jbphet** [comment]
@KatieWoe - This is quite an old issue that was seen on iOS only.  Can you please see if it can be duplicated on any of the iOS devices that you have available and, if not, close?

**Comment by KatieWoe** [comment]
I don't see this on iPadOS 14 on master. Do you want other platforms tested/published tested?

**Comment by jbphet** [comment]
No, I think the bug is old enough that if we're not seeing it on the latest iOS device and haven't had any other reports of it, it can be closed.
