### ISSUE TITLE
radius of "Reset All" button is duplicated in 2 places

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#73]
`radius: 20` duplicated at both calls to `new ResetAllButton`.  Noted while investigating https://github.com/phetsims/scenery-phet/issues/41.

**Comment by samreid** [comment]
At the moment, the game and non-game screens have different radii.  22 vs 20.  @pixelzoom OK to close?

**Comment by pixelzoom** [comment]
Please clarify. In master, it looks like they are all `radius: 20`:

```js
// BasicBalanceScreenView
    self.nonMassLayer.addChild( new ResetAllButton( {
      listener: resetClosure,
      radius: 20,
      right: indicatorVisibilityControlPanel.right,
      bottom: self.layoutBounds.height - 10,
      tandem: tandem.createTandem( 'resetAllButton' )
    } ) );

// StartGameLevelNode
    const resetButton = new ResetAllButton( { listener: resetFunction, radius: 20 } );
```

**Comment by samreid** [comment]
My apologies, I was looking at a stale branch as part of #45, I'm glad I checked with you.  I'll factor this out.

**Comment by pixelzoom** [comment]
Also recommended to remove `radius: 20` in both places.  In another issue (which I can't locate right now), the default was universally set in ResetAllButton.js, `RESET_ALL_BUTTON_RADIUS = 20.8`.  This is the value that should be used by all sims that are using default layoutBounds.

**Comment by pixelzoom** [comment]
Ah, the issue is https://github.com/phetsims/scenery-phet/issues/41, identified in the first comment of this issue.

**Comment by samreid** [comment]
Layout bounds for BA are currently:

```js
LAYOUT_BOUNDS: new Bounds2( 0, 0, 768, 504 )
```

Compare to ScreenView defaults:

```js
const DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );
```

**Comment by pixelzoom** [comment]
Does this sim have an issue to convert to DEFAULT_LAYOUT_BOUNDS?  I recall that we decided to do that for all sims. @ariel-phet ?

**Comment by ariel-phet** [comment]
It is certainly best to convert old sims to the new layout bounds when we revisit them. I don't think we necessarily decided to perform this work preemptively, but it would be appropriate for this simulation now that it is getting revisited.

**Comment by samreid** [comment]
I factored out the reset all button radius and opened a new issue for fixing the layout bounds.  Closing.
