### ISSUE TITLE
Random numbers should be reproducible

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#74]
From https://github.com/phetsims/phet-io/issues/548 the random numbers in this simulation should be reproducible.

**Comment by samreid** [comment]
Fixed above, @jbphet can you make sure this work is complete and correct?

**Comment by jbphet** [comment]
The changes look good, and I tested by running through two full levels on the sim's game screen and looking at the first challenge on two of them, and everything worked fine.  'Tis all good, closing.
