### ISSUE TITLE
Screenshot shows "adapted from PhET brand" not PhET brand

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balancing-act#77]
The screenshot currently on the website shows the "adapted from PhET" brand, not our normal logo. 

This oversight should be fixed in a maintenance release.

**Comment by ariel-phet** [comment]
Feel free to delegate to @aadish since I believe he knows the maintenance release process now.

**Comment by jbphet** [comment]
Fixed, now looks like this on the sim page:

![ba-screenshot](https://cloud.githubusercontent.com/assets/3082831/18972560/e63f498a-8656-11e6-9751-2f17906d97be.PNG)

Closing.
