### ISSUE TITLE
font for 'Position' is wrong

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#78]
Noted in https://github.com/phetsims/balancing-act/issues/58#issuecomment-265311019 by @ariel-phet. Font for 'Position' is wrong, it got smaller at some point. 

In master @c183b471a4c8b713fb1e1ea96bb2019c9061a964:

![screenshot_235](https://cloud.githubusercontent.com/assets/3046552/20949146/1eb920ac-bbd5-11e6-8806-ffd926bae18f.png)

In published 1.1.6:

![screenshot_236](https://cloud.githubusercontent.com/assets/3046552/20949178/4ac05472-bbd5-11e6-84ce-0656c55e9aea.png)

**Comment by pixelzoom** [comment]
Not sure how this every worked in a published version, because it's been broken since @jbphet's initial commit on 12/31/13. 

Here's the offending code:

```js
30 var PANEL_TITLE_FONT = new PhetFont( 16 );

72 new Text( positionString, PANEL_TITLE_FONT ),
```

Instead of passing options to Text, you were passing a font.  Fixed in above commit.

**Comment by pixelzoom** [comment]
@ariel-phet Please verify in http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.2.0-dev.2/balancing-act_en.html

**Comment by ariel-phet** [comment]
Looks good, closing
