### ISSUE TITLE
Reduce size of radio buttons

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balancing-act#80]
Our modern convention is to have the size of the radio button match the size of the first letter of the label. For instance 
![radio button](https://cloud.githubusercontent.com/assets/4051174/20978967/25f0fe60-bc68-11e6-917b-ea7b99b0a748.PNG)

The radio buttons on all screens are a bit oversized, they would be good to reduce to match convention. Not a high priority, but we are making a few tweaks to balancing act anyhow, so when those are being done would be good to also make this change

**Comment by jbphet** [comment]
Fixed, closing.
