### ISSUE TITLE
Create Sim Primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balancing-act#83]
- [x] Draft script - 6/12/18
- [x] Record rough version for script verification - 7/17/18
- [x] Review script verification draft, and adjust script as necessary - 7/18/18
<s> Record another draft </s>
<s> Review 2nd draft </s>
- [x] Produce primer and upload 
- [x] Caption primer

**Comment by arouinfar** [comment]
@CWilson4960 the Balancing Act script is now ready for recording.

**Comment by CWilson4960** [comment]
@arouinfar Balancing Act is uploaded to vimeo and has been captioned. Ready for review and uploading to the PhET website.
https://vimeo.com/280992581

**Comment by arouinfar** [comment]
Primer has been is live on the PhET site, thanks @CWilson4960!
