### ISSUE TITLE
Include mass label in click/touch area

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balancing-act#84]
In working on #83, I noticed that the 5 kg brick was a bit hard to grab. I found myself clicking on the mass string above the brick, which was unsuccessful. The click area is limited to the brick itself, but the touch area has been dilated a bit.

![image](https://user-images.githubusercontent.com/8419308/41170802-2c743542-6b0b-11e8-87d1-b2e7f0736af0.png)

I think the UX could be improved by expanding the click/touch areas to include the mass string above the objects. Items cannot be stacked onto one another, so making these areas a bit taller shouldn't have any funky side effects. 

![image](https://user-images.githubusercontent.com/8419308/41171383-8e02af58-6b0d-11e8-9f5f-8057af48563a.png)

@ariel-phet do you think this would be a worthwhile tweak next time Balancing Act has some dev attention? If not, please feel free to close.

**Comment by ariel-phet** [comment]
@arouinfar yes, that would be worthwhile.

**Comment by marlitas** [comment]
We can do this for the upcoming region and culture publication.
