### ISSUE TITLE
bad 'label' field in items passed to VerticalAquaRadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#88]
In PositionIndicatorControlPanel.js:

```js
    var positionMarkerRadioButtons = new VerticalAquaRadioButtonGroup( positionIndicatorStateProperty, [
      {
        node: new Text( noneString, RADIO_BUTTON_TEXT_OPTIONS ),
        value: 'none',
        label: noneString
      },
      {
        node: new Text( rulersString, RADIO_BUTTON_TEXT_OPTIONS ),
        value: 'rulers',
        label: rulersString
      },
      {
        node: new Text( marksString, RADIO_BUTTON_TEXT_OPTIONS ),
        value: 'marks',
        label: marksString
      }
    ], {
      radioButtonOptions: { radius: 6 },
      touchAreaXDilation: 5
    } );
```

According to the doc and implementation, the items passed to `VerticalAquaRadioButtonGroup` constructor have no `label` field.  And I could find no evidence in GitHub history that there ever was a `label` field.

No `@author` on the file, but looks like @jbphet.

EDIT: Updated above code to reflect changes for phetsims/sun#510.

**Comment by jbphet** [comment]
Removed unneeded labels, added author attribution.  Runs fine without these.  Closing.
