### ISSUE TITLE
Icons on home screen don't look very good on Firefox 27 and IE11

### ISSUE THREAD

**Issue by jbphet** [phetsims/balancing-act#9]
The icons for the home screen are sized according to the recommendations in the Screen.js file (548x373), but look pretty lousy on the home screen in Firefox and IE.  I think the image scaling algorithms for these browsers just isn't as good as in Chrome.  Basically, the plank looks very aliased.  See screen shots.

![ba-home-screen-ff](https://f.cloud.github.com/assets/3082831/2352437/da16f96e-a58a-11e3-90fd-38650f2bf45d.jpg)
![ba-home-screen-ie](https://f.cloud.github.com/assets/3082831/2352439/e0b8c48c-a58a-11e3-8b2b-034ddc9c7adc.jpg)

**Comment by elisemorgan** [comment]
Resolved in https://github.com/phetsims/tasks/issues/544
