### ISSUE TITLE
Small game icons with long strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#91]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found during https://github.com/phetsims/QA/issues/462. Very minor issue. Occurs in the published version.
The icons on the game screen get very small when strings are long

**Visuals**
![smallpictures](https://user-images.githubusercontent.com/41024075/71102728-3064ee80-2176-11ea-8cf4-4f6f9d9a8a25.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/balancing-act/1.1.24-rc.1/balancing-act_en.html?stringTest=long
Version: 1.1.24-rc.1 2019-12-17 18:52:29 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"6f134e0f","branch":"master"},"balancing-act":{"sha":"074ceb74","branch":"HEAD"},"brand":{"sha":"fbd39705","branch":"HEAD"},"chipper":{"sha":"cef07062","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"35017078","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"9ffe9bba","branch":"HEAD"},"phetcommon":{"sha":"06cf2532","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"7a2ba19a","branch":"HEAD"},"scenery-phet":{"sha":"afcc6f50","branch":"HEAD"},"sherpa":{"sha":"cd375f2a","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"efd6cf73","branch":"HEAD"}}

</details>

**Comment by jbphet** [comment]
This was found during a spot check of an RC that is intended to address a problem with touch dragging, see #43. As @KatieWoe points out above, this is present in the published version. It's never been reported as a problem, so I'm going to unassign, and we should plan on addressing this the next time this sim is release off of master.

**Comment by Luisav1** [comment]
Added `maxWidth` to the label text above the icon node, this now looks fixed. Tested it with stringTest=long below. Closing.
![image](https://github.com/phetsims/balancing-act/assets/52978048/8f218826-5465-430e-987f-ff6dd3e83a8b)
