### ISSUE TITLE
Overlap of long strings on ruler

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#92]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found during https://github.com/phetsims/QA/issues/462. Very minor issue. Occurs in published version.
When strings are long, they overlap on the ruler method of looking at position.

**Visuals**
![overlappingruler](https://user-images.githubusercontent.com/41024075/71106825-33171200-217d-11ea-9a18-37d1a10a721d.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/balancing-act/1.1.24-rc.1/balancing-act_en.html?stringTest=long
Version: 1.1.24-rc.1 2019-12-17 18:52:29 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"6f134e0f","branch":"master"},"balancing-act":{"sha":"074ceb74","branch":"HEAD"},"brand":{"sha":"fbd39705","branch":"HEAD"},"chipper":{"sha":"cef07062","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"35017078","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"9ffe9bba","branch":"HEAD"},"phetcommon":{"sha":"06cf2532","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"7a2ba19a","branch":"HEAD"},"scenery-phet":{"sha":"afcc6f50","branch":"HEAD"},"sherpa":{"sha":"cd375f2a","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"efd6cf73","branch":"HEAD"}}

</details>

**Comment by jbphet** [comment]
This was found during a spot check of an RC that is intended to address a problem with touch dragging, see https://github.com/phetsims/balancing-act/issues/43.  As @KatieWoe points out above, this is present in the published version.  It's never been reported as a problem, so I'm going to unassign, and we should plan on addressing this the next time this sim is release off of master.

**Comment by KatieWoe** [comment]
Another instance of strings being too long:
![toolong](https://user-images.githubusercontent.com/41024075/71115443-200d3d80-218f-11ea-8271-cb0a7d58423e.png)

**Comment by marlitas** [comment]
We can take a look at this as part of the upcoming region and culture publication.

**Comment by Luisav1** [comment]
I added a `maxWidth` to the Text nodes in `RotatingRulerNode` and `MassValueEntryNode`. Below is what those nodes now look like with `stringTest=long`. Closing.

![image](https://github.com/phetsims/balancing-act/assets/52978048/3dbb02ef-7973-44ad-9fa4-5888c42fc05e)
![image](https://github.com/phetsims/balancing-act/assets/52978048/70d7f2f4-5194-45fc-a4d4-d10aa619af4b)
