### ISSUE TITLE
Position Measurement setting is carried over between levels and is not reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#93]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/462. In the published version as well.
This bug pertains to the game screen. If you change the method of measuring position to ruler or marks in one level, it changes in the other levels as well. If you reset the game screen the measuring position method is not reset to its initial setting.

**Visuals**
![caryovernoreset](https://user-images.githubusercontent.com/41024075/71112926-cf471600-2189-11ea-9df7-94f30e0e6f02.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Balancing Act‬
URL: https://phet-dev.colorado.edu/html/balancing-act/1.1.24-rc.1/balancing-act_en.html
Version: 1.1.24-rc.1 2019-12-17 18:52:29 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"6f134e0f","branch":"master"},"balancing-act":{"sha":"074ceb74","branch":"HEAD"},"brand":{"sha":"fbd39705","branch":"HEAD"},"chipper":{"sha":"cef07062","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"35017078","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"9ffe9bba","branch":"HEAD"},"phetcommon":{"sha":"06cf2532","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"7a2ba19a","branch":"HEAD"},"scenery-phet":{"sha":"afcc6f50","branch":"HEAD"},"sherpa":{"sha":"cd375f2a","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"efd6cf73","branch":"HEAD"}}

</details>

**Comment by jbphet** [comment]
Unassigning, will address on next release off of master.

**Comment by marlitas** [comment]
We will address this in the upcoming publication.

**Comment by Luisav1** [comment]
In the commit above, `positionMarkerStateProperty` now resets when the reset button is clicked and whenever a level is started. See below. Closing.

https://github.com/phetsims/balancing-act/assets/52978048/1feca9ed-0cff-44af-bece-81508ccfaa74
