### ISSUE TITLE
Sitting in mid-air

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#95]
**Test device**
Dell
**Operating System**
Win 10 (touch)
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/462. Found in the same sort of manner as https://github.com/phetsims/balancing-act/issues/43, but much less harmful as it can be fixed by clicking on the bugged object and the sim does not need to be refreshed. It can still look very odd. Requires multitouch. Occurs in the published version.
If you pick up an object with one finger, and put another finger on it while holding it, it will act like you dropped it. You can then move the "sitting"object and drop it elsewhere, with the balance acting like it is in its initial position. Touching the object again fixes this. If you do this in a spot where it would return to the box it looks odd but doesn't seem to cause problems once you stop.
**Steps to reproduce**
1. Pull out one of the adults from the box so you can see the difference between sitting and standing and so you have more room. Use touch
2. While holding the person, use another finger to try and grab it.
3. Lift up the dropped skater with your first finger and then let go

**Visuals**
![floatingsit](https://user-images.githubusercontent.com/41024075/72298354-24583980-361b-11ea-947b-7c4efd4876ae.gif)
![midairsit](https://user-images.githubusercontent.com/41024075/72298355-24583980-361b-11ea-8781-c4cb40f4c6c1.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Balancing Act‬
URL: https://phet-dev.colorado.edu/html/balancing-act/1.1.24-rc.1/balancing-act_en.html
Version: 1.1.24-rc.1 2019-12-17 18:52:29 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"6f134e0f","branch":"master"},"balancing-act":{"sha":"074ceb74","branch":"HEAD"},"brand":{"sha":"fbd39705","branch":"HEAD"},"chipper":{"sha":"cef07062","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"35017078","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"9ffe9bba","branch":"HEAD"},"phetcommon":{"sha":"06cf2532","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"7a2ba19a","branch":"HEAD"},"scenery-phet":{"sha":"afcc6f50","branch":"HEAD"},"sherpa":{"sha":"cd375f2a","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"5df94328","branch":"HEAD"},"vibe":{"sha":"efd6cf73","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
What happens when done where it goes back to the box:
![doubledrop](https://user-images.githubusercontent.com/41024075/72360498-46020100-36ad-11ea-9936-42e19270d871.gif)
Flashing seems to happen more when screen recorder isn't on.

**Comment by jbphet** [comment]
I think my next steps to address this will be to try using event forwarding and `DragListener` instead of `SimpleDragHandler`.  Neither of these were available when the sim was originally written, and they probably handle multi-touch situations better than the older approaches.

**Comment by KatieWoe** [comment]
Occurs in https://github.com/phetsims/QA/issues/473.

**Comment by jbphet** [comment]
I made a number of modifications to drag handling, and it seems like the situation is improved.  I did not, however, change the creator nodes in the carousel to use event forwarding because of the amount of code that would need to change to accommodate this.  In order for event forwarding to work, the creator node has to have a way of obtaining the node that is created in the view, and it would have required a lot of refactoring - or some ugly hackery - to make this work.  In the end, I kept the overall architecture and modified things to handle multi-touch situations more elegantly.

@KatieWoe - please retest this on master.  The behavior is not perfect, but I have so far been unable to end up with objects in mid-air, and as long as that is the case, and no other big problems occur in these situations, I think we can call it an acceptable solution.  Please close if you agree or assign back if not.

**Comment by KatieWoe** [comment]
This still seems to occur, or something similar. If you do the above in a spot where it would go back to the toolbox, then move your finger above the balance then let go, you can get some of the more serious behavior from https://github.com/phetsims/balancing-act/issues/43. Sorry.
![funkyfly](https://user-images.githubusercontent.com/41024075/75823178-80f3ed00-5d5e-11ea-977e-065e7cd2937e.gif)
![moveover](https://user-images.githubusercontent.com/41024075/75823181-818c8380-5d5e-11ea-8f6e-c34a49590669.gif)

**Comment by KatieWoe** [comment]
This seems like it might be fixed along with #126 and #43 @jbphet

**Comment by jbphet** [comment]
> This seems like it might be fixed along with #126 and #43 @jbphet

Indeed, and I was about to assign it back to you to verify.  You're way ahead of me.  Please check and, if this can no longer be duplicated, assign it back to me.  I'd like to redeploy a version with this fixed.

**Comment by KatieWoe** [comment]
Seems fixed on master

**Comment by marlitas** [comment]
I will have QA verify in dev testing

**Comment by Nancy-Salpepi** [comment]
I can't reproduce this issue in 1.3.0-dev.1 but I will leave open for @KatieWoe to test.

**Comment by KatieWoe** [comment]
I wasn't able to reproduce either. Closing, but will reopen if we find again.
